spring:
  # 默认使用dev环境
  profiles:
    active: @spring.profiles.active@

#Mybatis
mybatis:
  mapper-locations: /xmls/*.xml
  configuration:
    call-setters-on-nulls: true
    cache-enabled: false
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
