spring:
  # 默认使用dev环境
  profiles:
    active: @spring.profiles.active@
  messages:
    #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    basename: i18n/messages
    #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
    cache-duration: -1ms
    #设定Message bundles的编码，默认: UTF-8
    encoding: UTF-8

#Mybatis
mybatis:
  mapper-locations: /xmls/*.xml
  configuration:
    call-setters-on-nulls: true
    cache-enabled: false
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


##jasypt加密的密匙
#jasypt:
#  encryptor:
#    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7